name: Build

on:
  workflow_call:

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: Staging
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        id: build
        run: |
          dotnet build --no-restore --configuration Release
          ls -la