name: Deploy

on:
  workflow_call:
    inputs:
      package-path:
        description: 'Path to the build .NET package'
        type: string

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Staging
    
    steps:
      - name: Print Package Path
        run: |
          find /home/runner/work -maxdepth 2 -type d -ls

      - name: Create package
        run: dotnet pack --configuration Release

      - name: Publish
        run: dotnet nuget push ${{ inputs.package-path }} "./MoneyExtension/bin/Release/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json