name: Build, Test and Deploy Package to Nuget

on:
  push:
    branches: [ "production", "staging" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    environment: 
      name: ${{ github.ref == 'refs/heads/production' && 'Production' || 'Staging' }}
      url: ${{ env.URL }}

    steps:
    - name: Set environment variable
      run: echo "URL=https://www.nuget.org/packages/${{ vars.PACKAGE_ID }}" >> $GITHUB_ENV

    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release -p:PackageId=${{ vars.PACKAGE_ID }}

    - name: Test
      run: dotnet test --verbosity normal

    - name: Publish
      run: dotnet nuget push "./MoneyExtension/bin/Release/${{ vars.PACKAGE_ID }}.*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json --skip-duplicate