name: Build, Test and Deploy Package - Staging

on:
  push:
    branches: [ "staging" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/staging/build/action.yml
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/staging/test/action.yml
  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/staging/deploy/.action.yml