name: Build, Test and Deploy Package - Staging

on:
  push:
    branches: [ "staging", "production" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: Staging

    steps:
      - uses: ./.github/workflows/build.yml

      - uses: ./.github/workflows/test.yml

      - uses: ./.github/workflows/deploy.yml